app/views/misc_views.py
# Copyright 2017 Twin Tech Labs. All rights reserved

from flask import Blueprint, redirect, render_template, current_app
from flask import request, url_for, flash, send_from_directory, jsonify, render_template_string
from flask_user import current_user, login_required, roles_accepted

from app import db
from app.models.user_models import UserProfileForm, User, UsersRoles
import uuid, json, os
import datetime

# When using a Flask app factory we must use a blueprint to avoid needing 'app' for '@app.route'
main_blueprint = Blueprint('main', __name__, template_folder='templates')

# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/')
def member_page():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))

    return render_template('pages/member_base.html')

# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_accepted('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('pages/admin/users.html')

@main_blueprint.route('/users')
@roles_accepted('admin')
def user_admin_page():
    users = User.query.all()
    return render_template('pages/admin/users.html',
        users=users)

@main_blueprint.route('/create_user', methods=['GET', 'POST'])
@roles_accepted('admin')
def create_user_page():
    form = UserProfileForm(request.form, obj=current_user)

    if request.method == 'POST':
        user = User.query.filter(User.email == request.form['email']).first()
        if not user:
            user = User(email=request.form['email'],
                        first_name=request.form['first_name'],
                        last_name=request.form['last_name'],
                        password=current_app.user_manager.hash_password(request.form['password']),
                        active=True,
                        email_confirmed_at=datetime.datetime.utcnow())
            db.session.add(user)
            db.session.commit()
        return redirect(url_for('main.user_admin_page'))
    return render_template('pages/admin/create_user.html',
                           form=form)

@main_blueprint.route('/delete_user', methods=['GET'])
@roles_accepted('admin')
def delete_user_page():
    try:
        user_id = request.args.get('user_id')

        db.session.query(UsersRoles).filter_by(user_id = user_id).delete()
        db.session.query(User).filter_by(id = user_id).delete()
        db.session.commit()

        flash('You successfully deleted your user!', 'success')
        return redirect(url_for('main.user_admin_page'))
    except Exception as e:
        flash('Opps!  Something unexpected happened.  On the brightside, we logged the error and will absolutely look at it and work to correct it, ASAP.', 'error')
        return redirect(request.referrer)

@main_blueprint.route('/pages/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.user_profile_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           current_user=current_user,
                           form=form)

app/templates/dark_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Twin Tech Labs - CoreUI Flask Admin</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Place favicon.ico and apple-touch-icon(s) in the root directory -->
        <link rel="shortcut icon" href="images/favicon.ico">

        <!-- stylesheets -->
        <link href="{{ url_for('static', filename='css/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/simple-line-icons/css/simple-line-icons.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

        <!-- javascript -->
        <script src="{{ url_for('static', filename='js/popper.js/dist/umd/popper.min.js') }}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/pace-progress/pace.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/perfect-scrollbar/dist/perfect-scrollbar.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/@coreui/coreui/dist/js/coreui.min.js') }}"></script>

        <script src="https://code.highcharts.com/highcharts.js"></script>
        <script src="https://code.highcharts.com/modules/exporting.js"></script>
        <script src="https://code.highcharts.com/modules/export-data.js"></script>
    </head>
    <body>
        {% block body %}
        <div class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
          <header class="app-header navbar">
            <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.member_page') }}">
              FlaskDash
            </a>
            <a class="nav-link nav-link--rounded pull-right" style="margin-right: 10px;" href="{{ url_for('user.logout') }}">
              Sign out
            </a>
          </header>
          <div class="app-body">
            <div class="sidebar">
              <nav class="sidebar-nav">
                <ul class="nav">
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.member_page') }}">
                      <i class="nav-icon icon-speedometer"></i> Dashboard
                      <span class="badge badge-primary">NEW</span>
                    </a>
                  </li>
                  <li class="nav-item nav-dropdown">
                    <a class="nav-link nav-dropdown-toggle" href="#">
                      <i class="nav-icon icon-bell"></i> My Account</a>
                    <ul class="nav-dropdown-items">
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.user_profile_page') }}">
                          <i class="nav-icon icon-drop"></i> Profile</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.change_password') }}">
                          <i class="nav-icon icon-drop"></i> Password</a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-title">Administration</li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.user_admin_page') }}">
                      <i class="nav-icon icon-drop"></i> Manage Users</a>
                  </li>
                </ul>
              </nav>
            </div>
          {% block pre_content %}{% endblock %}
          <main class="main">
          {# One-time system messages called Flash messages #}
          {% block flash_messages %}
              {%- with messages = get_flashed_messages(with_categories=true) -%}
                  {% if messages %}
                      {% for category, message in messages %}
                          {% if category=='error' %}
                              {% set category='danger' %}
                          {% endif %}
                          <div style="margin-bottom: -2px;" role="alert" class="alert alert-{{category}} alert-dismissible fade show">{{ message|safe }}</div>
                      {% endfor %}
                  {% endif %}
              {%- endwith %}
          {% endblock %}

          {% block content %}{% endblock %}
          </main>
          {% block post_content %}{% endblock %}

        {% endblock %}
        </div>
        <footer class="app-footer">
          <div>FlaskDash &copy; 2018 Twin Tech Labs</div>
          <div class="ml-auto">
            <span>Powered by</span>
            <a href="https://coreui.io">CoreUI</a>
            <span>(&copy; 2018 creativeLabs.)</span>
          </div>
        </footer>
      </div>
        <script>
            // Hide loader
            (function() {
                $(".alert").fadeTo(4000, 500).slideUp(500, function(){
                    $(".alert").slideUp(500);
                });
            })();
        </script>
    </body>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Twin Tech Labs - CoreUI Flask Admin</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Place favicon.ico and apple-touch-icon(s) in the root directory -->
        <link rel="shortcut icon" href="images/favicon.ico">

        <!-- stylesheets -->
        <link href="{{ url_for('static', filename='css/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/simple-line-icons/css/simple-line-icons.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

        <!-- javascript -->
        <script src="{{ url_for('static', filename='js/popper.js/dist/umd/popper.min.js') }}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/pace-progress/pace.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/perfect-scrollbar/dist/perfect-scrollbar.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/@coreui/coreui/dist/js/coreui.min.js') }}"></script>
    </head>
    <body>
        {% block body %}

        <div id="main-div" class="with-margins">
        {% block pre_content %}{% endblock %}

        {% block content %}{% endblock %}

        {% block post_content %}{% endblock %}
        </div>

        {% endblock %}

        <script>
            // Hide loader
            (function() {
                $(".alert").fadeTo(4000, 500).slideUp(500, function(){
                    $(".alert").slideUp(500);
                });
            })();
        </script>
    </body>
</html>